### ISSUE TITLE
Create Project Plan

### ISSUE THREAD

**Issue by ledamquangvinh** [ledamquangvinh/se-capstone-project#1]
Get information pf Project and Create Project plan Document

1. Kickoff Meeting with client.
2. Get draft requirement.
3. Create Project Plan document

**Comment by ledamquangvinh** [comment]
Kick-off meeting with client - Meeting note

> Requirement
>> 1. Build a online e-commerce for selling toys and teddy bears for children.
>> 2. The system support payment online for Vietnamese market.
>> 3. The client can monitor real-time sale statistics and get report for sales.

> Timeline for project is 1 month

> Technical Request is NONE.

**Comment by ledamquangvinh** [comment]
@ledamquangvinh  Create Project Plan 
- [x] Search and Create template for Project Plan
- [x] Create Project Plan Document with project information
- [x] Present with team and Public

**Comment by ledamquangvinh** [comment]
Using document template from https://sceweb.sce.uhcl.edu/helm/RUP_Folder/RationalUnifiedProcess/process/templates.htm
